server:
  port: 10000
spring:
  application:
    name: zuul
zuul:
  routes:
    card:
      url: http://localhost:10001
      strip-prefix: false
    player:
      url: http://localhost:10002
      strip-prefix: false
